modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"

[[mods]]
modId = "chaumtraft"
version = "${file.jarVersion}"
displayName = "Chaumtraft"

#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
#authors="Love, Cheese and small house plants"
displayTest="MATCH_VERSION"

description = '''

'''

[[dependencies.chaumtraft]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chaumtraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
